import './formatZhNumber';
import './formatColonTime';
import './formatLocalDate';
import CircleLinkedList from './circleLinkedList';
declare const easingMap: {
    'Cubic.easeInOut': string;
    'Cubic.easeIn': string;
    'Cubic.easeOut': string;
    'Sine.easeIn': string;
    'Sine.easeOut': string;
    'Sine.easeInOut': string;
    'Quad.easeIn': string;
    'Quad.easeOut': string;
    'Quad.easeInOut': string;
    'Quart.easeIn': string;
    'Quart.easeOut': string;
    'Quart.easeInOut': string;
    'Quint.easeIn': string;
    'Quint.easeOut': string;
    'Quint.easeInOut': string;
    'Expo.easeIn': string;
    'Expo.easeOut': string;
    'Expo.easeInOut': string;
    'Circ.easeIn': string;
    'Circ.easeOut': string;
    'Circ.easeInOut': string;
    'Back.easeIn': string;
    'Back.easeOut': string;
    'Back.easeInOut': string;
    Linear: string;
    Ease: string;
};
declare const fontSizePreset: any;
declare const circleLinkedDigit: CircleLinkedList;
declare const UUIDGenerator: () => string;
export { easingMap, fontSizePreset, UUIDGenerator, circleLinkedDigit };
//# sourceMappingURL=index.d.ts.map